### Exercise 1

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

B. Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

C. Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

In [17]:
import numpy as np

# A.
A = np.array([[i for i in range(1,11)]]) #this code will create an ndarray object(A) to store the values from 89 to 99
print("Array A:\n", A)

Array A:
 [[ 1  2  3  4  5  6  7  8  9 10]]


In [18]:
#1.
print("Shape:", A.shape) #This code line gets the size of A using the [variablename].shape function.

Shape: (1, 10)


In [19]:
# 2.
print("Maximum value", A.max()) # This code line gets the maximum value in the array A using the [variablename].max() function.

Maximum value 10


In [20]:
# 3.
print("Maximum value (using np.max):", np.max(A)) # this line of code will get the maximum value of the array in A using np.max(variablename) function

Maximum value (using np.max): 10


In [23]:
# B.
ones = np.ones((5, 5), dtype=int) #This code will make a 5x5 Integer-array filled with ones.
print("Array filled with ones:\n", ones)

print("\nShape of the array:", ones.shape) #this code will show the shape of the array using [variablename].shape
print("Size of the array:", ones.size) #this code will show the size of the array using [variablename].size
print("Number of dimensions of the array:", ones.ndim) #and this one will show the dimensions of the array using [variablename].ndim

Array filled with ones:
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

Shape of the array: (5, 5)
Size of the array: 25
Number of dimensions of the array: 2


In [24]:
# C.
original_array = np.arange(-5, 6) #1. This code will create an array ranging from -5 to 6

result_array = original_array * 2 # The original array will be multiplied by 2

print("Resulting array:", result_array) #2. this will print the resulting array

Resulting array: [-10  -8  -6  -4  -2   0   2   4   6   8  10]


### Exercise 2

A. Choose the values from the range of numbers 1 to 100.
1. Create an array with 30 values within the range of numbers given. You can choose your own start value and stop value. However, the incrementing value will be 2.
   * Explain what is the result briefly by writing a comment before the code.
2. Multiply the resulting array with 3. Print the result.

In [ ]:
#1. This code creates an array starting at 1 and ending at 60, with incrementing value of 2, which results to 30 values.
w = np.arange(1, 60, 2)
w

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59])

In [ ]:
#2.
multip = w*3
#3.
multip

array([  3,   9,  15,  21,  27,  33,  39,  45,  51,  57,  63,  69,  75,
        81,  87,  93,  99, 105, 111, 117, 123, 129, 135, 141, 147, 153,
       159, 165, 171, 177])

### Exercise 3

A. Create a four-dimensional array of random integers in the interval [0, 12]. Print the result.
1. Get the dimensions, shape, and size.
    * Explain what is the result briefly by writing a comment before the code.

B. Get the maximum number for each dimensions and display it.
   * Explain what is the result briefly by writing a comment before the code.

C. Multipy each array with 4. What is its result?
    * Write a brief explanation on the multiplication process.


#### Sample Method Calls:
```python
    np.random.rand()     #Will return a random number from a uniform distribution
    np.random.rand(10)   #Will return 10 random numbers from a uniform distribution
    np.random.rand(10,2) #Will return a 10x2 array of random numbers from a uniform distribution
```    
[あ]

In [ ]:
# A. this code generates a random 4-dimensional array of integers, then displays its dimensions, shape, and total size.
arr = np.random.randint(0, 13, size=(2, 3, 4, 5))
print("Random Array:")
print(arr)
print("\nDimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)

# B. this code finds the maximum value for each dimension of the array.
max_per_dim = arr.max(axis=(0, 1, 2, 3))
print("\nMax for each dimension:", max_per_dim)

# C. this code multiplies every element in the array by 4.
multiplied_arr = arr * 4
print(f"\nAfter Multiplying every element by 4: {multiplied_arr}")

Random Array:
[[[[ 9  6 11  3  8]
   [ 8  0  3  8  1]
   [ 8  2  4  2  8]
   [11 12  3  4  9]]

  [[11  3  2  5  8]
   [12  8  2  8 12]
   [ 1 11  4  5  9]
   [11  9  9 11 10]]

  [[ 8 12  0  9 10]
   [ 5  5 12  9  0]
   [ 7  6 11  6  2]
   [ 1  0  1  8  0]]]


 [[[ 5  7  0  7  0]
   [ 3 12  9  6  3]
   [ 2  0 10  1  2]
   [ 4  1 11  5  7]]

  [[ 2  8  6  1  7]
   [ 9  8 10  4  6]
   [ 1  9  8 10  7]
   [ 3  0  2 12  5]]

  [[10  0  0  8 11]
   [10  9  5  3 12]
   [12  8  0  7  9]
   [ 1  3  8  7 12]]]]

Dimensions: 4
Shape: (2, 3, 4, 5)
Size: 120

Max for each dimension: 12

After Multiplying every element by 4: [[[[36 24 44 12 32]
   [32  0 12 32  4]
   [32  8 16  8 32]
   [44 48 12 16 36]]

  [[44 12  8 20 32]
   [48 32  8 32 48]
   [ 4 44 16 20 36]
   [44 36 36 44 40]]

  [[32 48  0 36 40]
   [20 20 48 36  0]
   [28 24 44 24  8]
   [ 4  0  4 32  0]]]


 [[[20 28  0 28  0]
   [12 48 36 24 12]
   [ 8  0 40  4  8]
   [16  4 44 20 28]]

  [[ 8 32 24  4 28]
   [36 32 40 16 24]
   [ 4 36